### ISSUE TITLE
npm test genera una caterva di warning

### ISSUE THREAD

**Issue by xrmx** [tohacknight/open-hospital#11]
```
  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Not implemented: navigation (except hash changes)
        at module.exports (/home/rm/src/openhospital-ui/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
        at navigateFetch (/home/rm/src/openhospital-ui/node_modules/jsdom/lib/jsdom/living/window/navigation.js:74:3)
        at exports.navigate (/home/rm/src/openhospital-ui/node_modules/jsdom/lib/jsdom/living/window/navigation.js:52:3)
        at LocationImpl._locationObjectNavigate (/home/rm/src/openhospital-ui/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:29:5)
        at LocationImpl._locationObjectSetterNavigate (/home/rm/src/openhospital-ui/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:23:17)
        at LocationImpl.set pathname [as pathname] (/home/rm/src/openhospital-ui/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:151:10)
        at Location.set [as pathname] (/home/rm/src/openhospital-ui/node_modules/jsdom/lib/jsdom/living/generated/Location.js:293:31)
        at App.Object.<anonymous>.App.render (/home/rm/src/openhospital-ui/src/App.tsx:16:31)
        at finishClassComponent (/home/rm/src/openhospital-ui/node_modules/react-dom/cjs/react-dom.development.js:14535:31)
        at updateClassComponent (/home/rm/src/openhospital-ui/node_modules/react-dom/cjs/react-dom.development.js:14490:24) undefined

  console.error node_modules/history/node_modules/warning/warning.js:51
    Warning: You are attempting to use a basename on a page whose URL path does not begin with the basename. Expected path "/" to begin with "/undefined".

  console.error node_modules/prop-types/checkPropTypes.js:19
    Warning: Failed prop type: The property `spacing` of `Grid` must be used on `container`.
        in WithStyles(Grid) (created by Login)
        in Login (created by WithStyles(Login))
        in WithStyles(Login) (created by App)
        in Router (created by BrowserRouter)
        in BrowserRouter (created by App)
        in App
        in MuiThemeProviderOld
        in Unknown
```

**Comment by xrmx** [comment]
```
src/components/dashboard/MaterialPanel.tsx:32:97 - error TS2339: Property 'handleChange' does not exist on type 'MaterialPanel'.

32                 <Tabs className={classes.tabs} variant="fullWidth" value={value} onChange={this.handleChange}>
                                                                                                   ~~~~~~~~~~~~
src/components/dashboard/MaterialPanel.tsx:58:18 - error TS2367: This condition will always return 'false' since the types '0' and '1' have no overlap.

58                 {value === 1 && <TabContainer>Item Two</TabContainer>}
                    ~~~~~~~~~~~
src/components/dashboard/MaterialPanel.tsx:58:34 - error TS2304: Cannot find name 'TabContainer'.

58                 {value === 1 && <TabContainer>Item Two</TabContainer>}
                                    ~~~~~~~~~~~~
src/components/dashboard/MaterialPanel.tsx:58:57 - error TS2304: Cannot find name 'TabContainer'.

58                 {value === 1 && <TabContainer>Item Two</TabContainer>}
                                                           ~~~~~~~~~~~~
ts-jest[ts-compiler] (WARN) TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
src/components/patientsDatabase/PatientsListItem.tsx:25:17 - error TS2339: Property 'classes' does not exist on type 'Readonly<{ children?: ReactNode; }> & Readonly<{}>'.

25         const { classes, patient } = this.props;
                   ~~~~~~~
src/components/patientsDatabase/PatientsListItem.tsx:25:26 - error TS2339: Property 'patient' does not exist on type 'Readonly<{ children?: ReactNode; }> & Readonly<{}>'.

25         const { classes, patient } = this.props;
                            ~~~~~~~
src/components/patientsDatabase/PatientsListItem.tsx:32:97 - error TS2322: Type '{ pathname: string; patient: any; }' is not assignable to type 'LocationDescriptor<any>'.
  Object literal may only specify known properties, and 'patient' does not exist in type 'LocationDescriptorObject<any>'.

32                         to={{ pathname: PATH_PATIENT_DETAILS.replace(":patientId", patient.id), patient: patient }}>
                                                                                                   ~~~~~~~~~~~~~~~~

  node_modules/@types/react-router-dom/index.d.ts:48:5
    48     to: H.LocationDescriptor;
           ~~
    The expected type comes from property 'to' which is declared here on type 'IntrinsicAttributes & LinkProps'
src/components/patientsDatabase/PatientsListItem.tsx:70:22 - error TS2322: Type '{ children: Element; className: any; component: typeof Link; to: string; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

70                     <MaterialCardActionAreaRouter
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ts-jest[ts-compiler] (WARN) TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
src/components/sharedComponents/BreadcrumbTrail.tsx:43:23 - error TS7006: Parameter 'url' implicitly has an 'any' type.

43 const findRouteName = url => routes[url];
                         ~~~
src/components/sharedComponents/BreadcrumbTrail.tsx:45:19 - error TS7006: Parameter 'pathname' implicitly has an 'any' type.

45 const getPaths = (pathname) => {
                     ~~~~~~~~
src/components/sharedComponents/BreadcrumbTrail.tsx:50:33 - error TS7006: Parameter 'prev' implicitly has an 'any' type.

50     pathname.split('/').reduce((prev, curr, index) => {
                                   ~~~~
src/components/sharedComponents/BreadcrumbTrail.tsx:50:39 - error TS7006: Parameter 'curr' implicitly has an 'any' type.

50     pathname.split('/').reduce((prev, curr, index) => {
                                         ~~~~
src/components/sharedComponents/BreadcrumbTrail.tsx:50:45 - error TS7006: Parameter 'index' implicitly has an 'any' type.

50     pathname.split('/').reduce((prev, curr, index) => {
                                               ~~~~~
src/components/sharedComponents/BreadcrumbTrail.tsx:59:21 - error TS7006: Parameter 'match' implicitly has an 'any' type.

59 const prepareUrl = (match, path) => {
                       ~~~~~
src/components/sharedComponents/BreadcrumbTrail.tsx:59:28 - error TS7006: Parameter 'path' implicitly has an 'any' type.

59 const prepareUrl = (match, path) => {
                              ~~~~
src/components/sharedComponents/BreadcrumbTrail.tsx:69:26 - error TS7006: Parameter 'props' implicitly has an 'any' type.

69 const BreadcrumbsItem = (props) => {
                            ~~~~~
src/components/sharedComponents/BreadcrumbTrail.tsx:78:15 - error TS2322: Type '{ children: any; color: string; component: typeof Link; to: any; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

78             (<MaterialLinkRouter
                 ~~~~~~~~~~~~~~~~~~
src/components/sharedComponents/BreadcrumbTrail.tsx:89:30 - error TS7006: Parameter 'props' implicitly has an 'any' type.

89 const BreadcrumbContainer = (props) => {
                                ~~~~~
src/components/sharedComponents/BreadcrumbTrail.tsx:91:13 - error TS2339: Property 'props' does not exist on type 'Console'.

91     console.props
               ~~~~~
src/components/sharedComponents/BreadcrumbTrail.tsx:99:16 - error TS7006: Parameter 'props' implicitly has an 'any' type.

99 export default props => (
                  ~~~~~
ts-jest[ts-compiler] (WARN) TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
src/components/patientsDatabase/PatientVisit.tsx:49:5 - error TS2741: Property 'InputLabelRef' is missing in type '{ labelWidth: number; error: null; isLoaded: false; items: never[]; openOptionalInfo: false; anchorEl: null; }' but required in type 'State'.

49     state: State = {
       ~~~~~

  src/components/patientsDatabase/PatientVisit.tsx:39:5
    39     InputLabelRef: number;
           ~~~~~~~~~~~~~
    'InputLabelRef' is declared here.
src/components/patientsDatabase/PatientVisit.tsx:63:26 - error TS2339: Property 'patient' does not exist on type 'Readonly<{ children?: ReactNode; }> & Readonly<Props>'.

63         const { classes, patient } = this.props;
                            ~~~~~~~
src/components/patientsDatabase/PatientVisit.tsx:129:75 - error TS2339: Property 'detailButtonLabel' does not exist on type 'Record<"object" | "select" | "table" | "root" | "gridContainer" | "divider" | "breadCrumb" | "paper" | "paperFlat" | "formField" | "formFieldInputLabel" | "cssOutlinedInput" | "cssFocused" | ... 85 more ... | "colleagueContainer", string>'.

129                     classes={{ root: classes.detailButton, label: classes.detailButtonLabel }}>
                                                                              ~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/PatientVisit.tsx:160:26 - error TS2322: Type '{ children: string; component: typeof Link; to: string; variant: string; color: string; classes: { root: string; label: any; }; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

160                         <MaterialButtonRouter component={LinkRouter} to={PATH_PATIENT_THERAPY.replace(':patientId', patient.id)} variant="outlined" color="inherit" classes={{ root: classes.detailButtonTherapy, label: classes.detailButtonLabel }}>
                             ~~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/PatientVisit.tsx:160:226 - error TS2339: Property 'detailButtonLabel' does not exist on type 'Record<"object" | "select" | "table" | "root" | "gridContainer" | "divider" | "breadCrumb" | "paper" | "paperFlat" | "formField" | "formFieldInputLabel" | "cssOutlinedInput" | "cssFocused" | ... 85 more ... | "colleagueContainer", string>'.

160                         <MaterialButtonRouter component={LinkRouter} to={PATH_PATIENT_THERAPY.replace(':patientId', patient.id)} variant="outlined" color="inherit" classes={{ root: classes.detailButtonTherapy, label: classes.detailButtonLabel }}>
                                                                                                                                                                                                                                     ~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/PatientVisit.tsx:219:82 - error TS2339: Property 'formFieldSelectService' does not exist on type 'Record<"object" | "select" | "table" | "root" | "gridContainer" | "divider" | "breadCrumb" | "paper" | "paperFlat" | "formField" | "formFieldInputLabel" | "cssOutlinedInput" | "cssFocused" | ... 85 more ... | "colleagueContainer", string>'.

219                                 className={classNames(classes.formField, classes.formFieldSelectService)}>
                                                                                     ~~~~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/PatientVisit.tsx:222:46 - error TS2339: Property 'InputLabelRef' does not exist on type 'PatientVisit'.

222                                         this.InputLabelRef = ref;
                                                 ~~~~~~~~~~~~~
src/components/patientsDatabase/PatientVisit.tsx:251:22 - error TS2322: Type '{ children: (string | Element)[]; component: typeof Link; to: string; variant: string; color: string; classes: { root: string; label: string; }; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

251                     <MaterialButtonRouter
                         ~~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/PatientVisit.tsx:260:22 - error TS2322: Type '{ children: (string | Element)[]; component: typeof Link; to: string; variant: string; color: string; classes: { root: string; }; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

260                     <MaterialButtonRouter
                         ~~~~~~~~~~~~~~~~~~~~
ts-jest[ts-compiler] (WARN) TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
src/components/patientsDatabase/NewOpd.tsx:44:26 - error TS2339: Property 'patient' does not exist on type 'Readonly<{ children?: ReactNode; }> & Readonly<Props>'.

44         const { classes, patient } = this.props;
                            ~~~~~~~
src/components/patientsDatabase/NewOpd.tsx:61:28 - error TS2322: Type '24' is not assignable to type 'boolean | 1 | 2 | 12 | 10 | 8 | "auto" | 5 | 3 | 4 | 6 | 7 | 9 | 11 | undefined'.

61                 <Grid item xs={24} justify="center" className={classes.patientRadioOpd}>
                              ~~
src/components/patientsDatabase/NewOpd.tsx:111:18 - error TS2322: Type '{ title: string; }' is not assignable to type 'IntrinsicAttributes & Pick<Props, never> & StyledComponentProps<"title" | "formField" | "formFieldInputLabel" | "container" | "formFieldSelect" | "formFieldSelectInput" | "selectLabel" | "inputBody"> & { ...; }'.
  Property 'title' does not exist on type 'IntrinsicAttributes & Pick<Props, never> & StyledComponentProps<"title" | "formField" | "formFieldInputLabel" | "container" | "formFieldSelect" | "formFieldSelectInput" | "selectLabel" | "inputBody"> & { ...; }'.

111                 <Spinner title="DESEASE TYPE"/>
                     ~~~~~~~
src/components/patientsDatabase/NewOpd.tsx:112:18 - error TS2322: Type '{ title: string; }' is not assignable to type 'IntrinsicAttributes & Pick<Props, never> & StyledComponentProps<"title" | "formField" | "formFieldInputLabel" | "container" | "formFieldSelect" | "formFieldSelectInput" | "selectLabel" | "inputBody"> & { ...; }'.
  Property 'title' does not exist on type 'IntrinsicAttributes & Pick<Props, never> & StyledComponentProps<"title" | "formField" | "formFieldInputLabel" | "container" | "formFieldSelect" | "formFieldSelectInput" | "selectLabel" | "inputBody"> & { ...; }'.

112                 <Spinner title="DIAGNOSIS"/>
                     ~~~~~~~
src/components/patientsDatabase/NewOpd.tsx:113:18 - error TS2322: Type '{ title: string; }' is not assignable to type 'IntrinsicAttributes & Pick<Props, never> & StyledComponentProps<"title" | "formField" | "formFieldInputLabel" | "container" | "formFieldSelect" | "formFieldSelectInput" | "selectLabel" | "inputBody"> & { ...; }'.
  Property 'title' does not exist on type 'IntrinsicAttributes & Pick<Props, never> & StyledComponentProps<"title" | "formField" | "formFieldInputLabel" | "container" | "formFieldSelect" | "formFieldSelectInput" | "selectLabel" | "inputBody"> & { ...; }'.

113                 <Spinner title="DIAGNOSIS N°2"/>
                     ~~~~~~~
src/components/patientsDatabase/NewOpd.tsx:114:18 - error TS2322: Type '{ title: string; }' is not assignable to type 'IntrinsicAttributes & Pick<Props, never> & StyledComponentProps<"title" | "formField" | "formFieldInputLabel" | "container" | "formFieldSelect" | "formFieldSelectInput" | "selectLabel" | "inputBody"> & { ...; }'.
  Property 'title' does not exist on type 'IntrinsicAttributes & Pick<Props, never> & StyledComponentProps<"title" | "formField" | "formFieldInputLabel" | "container" | "formFieldSelect" | "formFieldSelectInput" | "selectLabel" | "inputBody"> & { ...; }'.

114                 <Spinner title="DIAGNOSIS N°3"/>
                     ~~~~~~~
src/components/patientsDatabase/NewOpd.tsx:138:22 - error TS2322: Type '{ children: (string | Element)[]; component: typeof Link; to: string; variant: string; color: string; classes: { root: string; label: string; }; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

138                     <MaterialButtonRouter
                         ~~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewOpd.tsx:147:22 - error TS2322: Type '{ children: (string | Element)[]; component: typeof Link; to: string; variant: string; color: string; classes: { root: string; label: string; }; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

147                     <MaterialButtonRouter
                         ~~~~~~~~~~~~~~~~~~~~
ts-jest[ts-compiler] (WARN) TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
src/components/patientsDatabase/PatientVaccination.tsx:8:26 - error TS7016: Could not find a declaration file for module 'mui-datatables'. '/home/rm/src/openhospital-ui/node_modules/mui-datatables/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/mui-datatables` if it exists or add a new declaration (.d.ts) file containing `declare module 'mui-datatables';`

8 import MUIDataTable from "mui-datatables";
                           ~~~~~~~~~~~~~~~~
src/components/patientsDatabase/PatientVaccination.tsx:38:26 - error TS2339: Property 'patient' does not exist on type 'Readonly<{ children?: ReactNode; }> & Readonly<Props>'.

38         const { classes, patient } = this.props;
                            ~~~~~~~
src/components/patientsDatabase/PatientVaccination.tsx:76:26 - error TS2322: Type '{ children: string; component: typeof Link; to: string; variant: string; color: string; classes: { root: string; label: any; }; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

76                         <MaterialButtonRouter component={LinkRouter} to={PATH_PATIENT_NEW_VACCINATION.replace(':patientId', patient.id)} variant="outlined" color="inherit" classes={{ root: classes.detailNewVaccineButton, label: classes.detailButtonLabel }}>
                            ~~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/PatientVaccination.tsx:76:237 - error TS2339: Property 'detailButtonLabel' does not exist on type 'Record<"object" | "select" | "table" | "root" | "gridContainer" | "divider" | "breadCrumb" | "paper" | "paperFlat" | "formField" | "formFieldInputLabel" | "cssOutlinedInput" | "cssFocused" | ... 87 more ... | "detailNewVaccineButton", string>'.

76                         <MaterialButtonRouter component={LinkRouter} to={PATH_PATIENT_NEW_VACCINATION.replace(':patientId', patient.id)} variant="outlined" color="inherit" classes={{ root: classes.detailNewVaccineButton, label: classes.detailButtonLabel }}>
                                                                                                                                                                                                                                               ~~~~~~~~~~~~~~~~~
ts-jest[ts-compiler] (WARN) TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
src/components/patientsDatabase/NewVaccination.tsx:41:26 - error TS2339: Property 'patient' does not exist on type 'Readonly<{ children?: ReactNode; }> & Readonly<Props>'.

41         const { classes, patient } = this.props;
                            ~~~~~~~
src/components/patientsDatabase/NewVaccination.tsx:87:78 - error TS2339: Property 'formFieldSelectService' does not exist on type 'Record<"object" | "select" | "table" | "root" | "gridContainer" | "divider" | "breadCrumb" | "paper" | "paperFlat" | "formField" | "formFieldInputLabel" | "cssOutlinedInput" | "cssFocused" | ... 83 more ... | "colleagueContainer", string>'.

87                             className={classNames(classes.formField, classes.formFieldSelectService)}>
                                                                                ~~~~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewVaccination.tsx:90:42 - error TS2339: Property 'InputLabelRef' does not exist on type 'Vaccine'.

90                                     this.InputLabelRef = ref;
                                            ~~~~~~~~~~~~~
src/components/patientsDatabase/NewVaccination.tsx:100:64 - error TS2339: Property 'InputLabelRef' does not exist on type 'State'.

100                                         labelWidth={this.state.InputLabelRef}
                                                                   ~~~~~~~~~~~~~
src/components/patientsDatabase/NewVaccination.tsx:119:78 - error TS2339: Property 'formFieldSelectService' does not exist on type 'Record<"object" | "select" | "table" | "root" | "gridContainer" | "divider" | "breadCrumb" | "paper" | "paperFlat" | "formField" | "formFieldInputLabel" | "cssOutlinedInput" | "cssFocused" | ... 83 more ... | "colleagueContainer", string>'.

119                             className={classNames(classes.formField, classes.formFieldSelectService)}>
                                                                                 ~~~~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewVaccination.tsx:122:42 - error TS2339: Property 'InputLabelRef' does not exist on type 'Vaccine'.

122                                     this.InputLabelRef = ref;
                                             ~~~~~~~~~~~~~
src/components/patientsDatabase/NewVaccination.tsx:132:60 - error TS2339: Property 'InputLabelRef' does not exist on type 'State'.

132                                     labelWidth={this.state.InputLabelRef}
                                                               ~~~~~~~~~~~~~
src/components/patientsDatabase/NewVaccination.tsx:168:26 - error TS2322: Type '{ children: (string | Element)[]; component: typeof Link; to: string; variant: string; color: string; classes: { root: string; label: string; }; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

168                         <MaterialButtonRouter
                             ~~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewVaccination.tsx:177:26 - error TS2322: Type '{ children: (string | Element)[]; component: typeof Link; to: string; variant: string; color: string; classes: { root: string; label: string; }; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

177                         <MaterialButtonRouter
                             ~~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewVaccination.tsx:186:26 - error TS2322: Type '{ children: (string | Element)[]; component: typeof Link; to: string; variant: string; color: string; classes: { root: string; label: string; }; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

186                         <MaterialButtonRouter
                             ~~~~~~~~~~~~~~~~~~~~
ts-jest[ts-compiler] (WARN) TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
src/components/patientsDatabase/NewLabTest.tsx:41:26 - error TS2339: Property 'patient' does not exist on type 'Readonly<{ children?: ReactNode; }> & Readonly<Props>'.

41         const { classes, patient } = this.props;
                            ~~~~~~~
src/components/patientsDatabase/NewLabTest.tsx:86:78 - error TS2339: Property 'formFieldSelectService' does not exist on type 'Record<"object" | "select" | "table" | "root" | "gridContainer" | "divider" | "breadCrumb" | "paper" | "paperFlat" | "formField" | "formFieldInputLabel" | "cssOutlinedInput" | "cssFocused" | ... 83 more ... | "colleagueContainer", string>'.

86                             className={classNames(classes.formField, classes.formFieldSelectService)}>
                                                                                ~~~~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewLabTest.tsx:89:42 - error TS2339: Property 'InputLabelRef' does not exist on type 'NewLabTest'.

89                                     this.InputLabelRef = ref;
                                            ~~~~~~~~~~~~~
src/components/patientsDatabase/NewLabTest.tsx:100:64 - error TS2339: Property 'InputLabelRef' does not exist on type 'State'.

100                                         labelWidth={this.state.InputLabelRef}
                                                                   ~~~~~~~~~~~~~
src/components/patientsDatabase/NewLabTest.tsx:135:26 - error TS2322: Type '{ children: (string | Element)[]; component: typeof Link; to: string; variant: string; color: string; classes: { root: string; label: string; }; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

135                         <MaterialButtonRouter
                             ~~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewLabTest.tsx:144:26 - error TS2322: Type '{ children: (string | Element)[]; component: typeof Link; to: string; variant: string; color: string; classes: { root: string; label: string; }; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

144                         <MaterialButtonRouter
                             ~~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewLabTest.tsx:153:26 - error TS2322: Type '{ children: (string | Element)[]; component: typeof Link; to: string; variant: string; color: string; classes: { root: string; label: string; }; }' is not assignable to type 'IntrinsicAttributes & LinkProps'.
  Property 'component' does not exist on type 'IntrinsicAttributes & LinkProps'.

153                         <MaterialButtonRouter
                             ~~~~~~~~~~~~~~~~~~~~
ts-jest[ts-compiler] (WARN) TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
src/components/patientsDatabase/NewPatient.tsx:47:17 - error TS7006: Parameter 'props' implicitly has an 'any' type.

47     constructor(props) {
                   ~~~~~
src/components/patientsDatabase/NewPatient.tsx:49:24 - error TS2322: Type '{ snackbaropen: boolean; snackbarmsg: string; }' is not assignable to type 'State'.
  Object literal may only specify known properties, and 'snackbaropen' does not exist in type 'State'.

49         this.state = { snackbaropen: false, snackbarmsg: '' };
                          ~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:54:13 - error TS2322: Type '{ firstName: string; secondName: string; name: string; birthDate: any; age: number; agetype: string; sex: string; taxCode: string; address: string; city: string; telephone: string; nextKin: string; bloodType: string; ... 4 more ...; lock: number; }' is not assignable to type 'State'.
  Object literal may only specify known properties, and 'firstName' does not exist in type 'State'.

54             firstName: "",
               ~~~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:57:24 - error TS2554: Expected 0 arguments, but got 1.

57             birthDate: Date("1968-07-17"),
                          ~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:75:22 - error TS7006: Parameter 'event' implicitly has an 'any' type.

75     snackbarClose = (event) => {
                        ~~~~~
src/components/patientsDatabase/NewPatient.tsx:76:25 - error TS2345: Argument of type '{ snackbaropen: boolean; }' is not assignable to parameter of type 'State | Pick<State, "error" | "labelWidth" | "isLoaded" | "items" | "anchorEl"> | ((prevState: Readonly<State>, props: Readonly<IProps>) => State | Pick<State, "error" | "labelWidth" | "isLoaded" | "items" | "anchorEl"> | null) | null'.
  Object literal may only specify known properties, and 'snackbaropen' does not exist in type 'State | Pick<State, "error" | "labelWidth" | "isLoaded" | "items" | "anchorEl"> | ((prevState: Readonly<State>, props: Readonly<IProps>) => State | Pick<State, "error" | "labelWidth" | "isLoaded" | "items" | "anchorEl"> | null)'.

76         this.setState({ snackbaropen: false });
                           ~~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:79:21 - error TS7006: Parameter 'event' implicitly has an 'any' type.

79     handleChange = (event) => {
                       ~~~~~
src/components/patientsDatabase/NewPatient.tsx:80:23 - error TS2345: Argument of type '{ [x: number]: any; }' is not assignable to parameter of type 'State | Pick<State, "error" | "labelWidth" | "isLoaded" | "items" | "anchorEl"> | ((prevState: Readonly<State>, props: Readonly<IProps>) => State | Pick<State, "error" | "labelWidth" | "isLoaded" | "items" | "anchorEl"> | null) | null'.
  Type '{ [x: number]: any; }' is not assignable to type '(prevState: Readonly<State>, props: Readonly<IProps>) => State | Pick<State, "error" | "labelWidth" | "isLoaded" | "items" | "anchorEl"> | null'.
    Type '{ [x: number]: any; }' provides no match for the signature '(prevState: Readonly<State>, props: Readonly<IProps>): State | Pick<State, "error" | "labelWidth" | "isLoaded" | "items" | "anchorEl"> | null'.

80         this.setState({
                         ~
81             [event.target.name]: event.target.value
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
82         });
   ~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:85:18 - error TS7006: Parameter 'event' implicitly has an 'any' type.

85     handleSubmit(event) {
                    ~~~~~
src/components/patientsDatabase/NewPatient.tsx:89:15 - error TS6133: 'classes' is declared but its value is never read.

89         const { classes } = this.props;
                 ~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:91:61 - error TS2559: Type 'State' has no properties in common with type 'Patient'.

91         const requestParams: NewPatientUsingPOSTRequest = { newPatient: Patient };
                                                               ~~~~~~~~~~

  src/generate/apis/PatientControllerApi.ts:36:5
    36     newPatient: Patient;
           ~~~~~~~~~~
    The expected type comes from property 'newPatient' which is declared here on type 'NewPatientUsingPOSTRequest'
src/components/patientsDatabase/NewPatient.tsx:107:37 - error TS2345: Argument of type '{ snackbaropen: boolean; snackbarmsg: string; }' is not assignable to parameter of type 'State | Pick<State, "error" | "labelWidth" | "isLoaded" | "items" | "anchorEl"> | ((prevState: Readonly<State>, props: Readonly<IProps>) => State | Pick<State, "error" | "labelWidth" | "isLoaded" | "items" | "anchorEl"> | null) | null'.
  Object literal may only specify known properties, and 'snackbaropen' does not exist in type 'State | Pick<State, "error" | "labelWidth" | "isLoaded" | "items" | "anchorEl"> | ((prevState: Readonly<State>, props: Readonly<IProps>) => State | Pick<State, "error" | "labelWidth" | "isLoaded" | "items" | "anchorEl"> | null)'.

107                     this.setState({ snackbaropen: true, snackbarmsg: "ERROR!! : (check if the data has been entered correctly)" })
                                        ~~~~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:118:38 - error TS2339: Property 'snackbaropen' does not exist on type 'State'.

118                     open={this.state.snackbaropen}
                                         ~~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:120:39 - error TS2322: Type '{ direction: string; }' is not assignable to type 'TransitionProps'.
  Object literal may only specify known properties, and 'direction' does not exist in type 'TransitionProps'.

120                     TransitionProps={{direction: "left"}}
                                          ~~~~~~~~~~~~~~~~~

  node_modules/@material-ui/core/Snackbar/Snackbar.d.ts:31:3
    31   TransitionProps?: TransitionProps;
         ~~~~~~~~~~~~~~~
    The expected type comes from property 'TransitionProps' which is declared here on type 'IntrinsicAttributes & SnackbarProps & { children?: ReactNode; }'
src/components/patientsDatabase/NewPatient.tsx:124:80 - error TS2339: Property 'snackbarmsg' does not exist on type 'State'.

124                         message={<span className={classes.message}>{this.state.snackbarmsg}</span>}/>
                                                                                   ~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:130:68 - error TS2339: Property 'match' does not exist on type 'Readonly<{ children?: ReactNode; }> & Readonly<IProps>'.

130                                 <BreadcrumbTrail match={this.props.match}/>
                                                                       ~~~~~
src/components/patientsDatabase/NewPatient.tsx:151:84 - error TS2339: Property 'formDescription' does not exist on type 'Record<"select" | "root" | "gridContainer" | "divider" | "breadCrumb" | "paper" | "paperFlat" | "formField" | "formFieldInputLabel" | "cssOutlinedInput" | "cssFocused" | "icon" | ... 54 more ... | "message", string>'.

151                                     <Typography color="inherit" className={classes.formDescription}>
                                                                                       ~~~~~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:257:62 - error TS2339: Property 'InputLabelRef' does not exist on type 'NewPatient'.

257                                                         this.InputLabelRef = ref;
                                                                 ~~~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:271:58 - error TS2322: Type '{ labelWidth: any; label: string; name: string; classes: { input: string; }; }' is not assignable to type 'IntrinsicAttributes & OutlinedInputProps & { children?: ReactNode; }'.
  Property 'label' does not exist on type 'IntrinsicAttributes & OutlinedInputProps & { children?: ReactNode; }'.

271                                                         <OutlinedInput
                                                             ~~~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:272:80 - error TS2339: Property 'InputLabelRef' does not exist on type 'State'.

272                                                         labelWidth={this.state.InputLabelRef}
                                                                                   ~~~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:437:64 - error TS2339: Property 'test' does not exist on type 'Record<"select" | "root" | "gridContainer" | "divider" | "breadCrumb" | "paper" | "paperFlat" | "formField" | "formFieldInputLabel" | "cssOutlinedInput" | "cssFocused" | "icon" | ... 54 more ... | "message", string>'.

437                                             className={classes.test}>
                                                                   ~~~~
src/components/patientsDatabase/NewPatient.tsx:449:62 - error TS2339: Property 'InputLabelRef' does not exist on type 'NewPatient'.

449                                                         this.InputLabelRef = ref;
                                                                 ~~~~~~~~~~~~~
src/components/patientsDatabase/NewPatient.tsx:464:84 - error TS2339: Property 'InputLabelRef' does not exist on type 'State'.

464
```
